# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-29 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_more_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='discription',
            new_name='description',
        ),
    ]
